[project]
site_name = "WARP - Create Widgets in KMP"
site_description = "WARP — Widget Abstraction & Rendering Pipeline for KMP. Write widget UI once in Kotlin; render on Android (Glance) and iOS (WidgetKit)"
site_url="https://warp.atherio.dev"
repo_name = "devatrii/warp"
repo_url="https://github.com/DevAtrii/Warp"
nav = [
  {"Home" = "index.html"},
  {"Mental Model" = "1-mental-model.md"},

  {"Documentation" = [
    "docs/1-setup.md",
    "docs/2-creating-your-first-widget.md",
    "docs/3-warp-composables.md",
    "docs/4-warp-theme.md",
    "docs/5-warp-adaptive.md",
  ]},
  {"How WARP Works" = "2-how-warp-works.md"},
  {"Create with AI" = "docs/3-create-with-ai.md"},
  {"Widget Wizard" = "wizard.html"},
]


[project.theme]
logo = "assets/logo.webp"
favicon = "assets/favicon/favicon.ico"
features = [
  "navigation.footer",
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.instant.progress",
  "navigation.tabs",
  "navigation.tabs.sticky",
  "navigation.path",
  "navigation.top",
  "search.suggest",
  "search.highlight",
  "content.code.copy",
  "content.code.annotate",
  "content.code.select",
  "content.tooltips"
]

[[project.theme.palette]]
scheme = "slate"
primary = "green"
accent = "green"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"
primary = "green"
accent = "green"




[project.extra.analytics.feedback]
title = "Was this page helpful?"

[[project.extra.analytics.feedback.ratings]]
icon = "material/emoticon-happy-outline"
name = "This page was helpful"
data = 1
note = "Thanks for your feedback!"

[[project.extra.analytics.feedback.ratings]]
icon = "material/emoticon-sad-outline"
name = "This page could be improved"
data = 0
note = """
  Thanks for your feedback! Help us improve this page by
  using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
"""


[markdown_extensions]
admonition = {}
footnotes = {}
def_list = {}
"pymdownx.details" = {}
"pymdownx.superfences" = {}
"pymdownx.inlinehilite" = {}
"pymdownx.snippets" = {}
copy_button = {}
attr_list = {}
md_in_html = {}

# socials
[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/DevAtrii/Warp"

[[project.extra.social]]
icon = "fontawesome/brands/x-twitter"
link = "https://x.com/dev_atrii"

[[project.extra.social]]
icon = "fontawesome/brands/youtube"
link = "https://youtube.com/@devatrii"